# Generated by Django 4.2.13 on 2024-05-23 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=12)),
                ('vehicle_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
