# Generated by Django 4.2.13 on 2024-05-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
