# Generated by Django 5.0 on 2024-05-10 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/owner_images/')),
                ('mobile_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('nid_card_no', models.CharField(max_length=11)),
                ('slot_size', models.CharField(max_length=200)),
                ('capacity', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('area', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=200)),
                ('card_no', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('park_owner_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
