# Generated by Django 5.0 on 2024-05-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkowner',
            old_name='park_owner_id',
            new_name='user',
        ),
    ]
