# Generated by Django 5.0 on 2024-05-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_park_owner_id_parkowner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkowner',
            old_name='user',
            new_name='park_owner_id',
        ),
        migrations.RemoveField(
            model_name='parkowner',
            name='card_no',
        ),
    ]
