# Generated by Django 5.0 on 2024-05-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_parkowner_park_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkowner',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parkowner',
            name='payment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkowner',
            name='payment_method',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
