# Generated by Django 4.2.13 on 2024-05-11 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_parkowner_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_plan', models.ImageField(blank=True, null=True, upload_to='media/park_plans/')),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('park_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_details', to='accounts.parkowner')),
            ],
        ),
    ]
