# Generated by Django 4.2.13 on 2024-05-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_park_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park_detail',
            name='park_plan',
        ),
        migrations.AddField(
            model_name='park_detail',
            name='park_plan_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
