# Generated by Django 4.2.13 on 2024-05-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_park_detail_park_plan_park_detail_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=12)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('nid_card_no', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='park_detail',
            name='capacity',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', models.IntegerField(blank=True, default=0, null=True)),
                ('time_slot', models.IntegerField(choices=[('1', '1 Hours'), ('2', '3 Hours'), ('3', '5 Hours')])),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('park_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.park_detail')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicle')),
            ],
        ),
    ]
