# Generated by Django 4.2.13 on 2024-05-14 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_park_detail_park_plan_text_booking_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='park_detail',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='park_owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='park_owner', to='accounts.parkowner'),
        ),
        migrations.AddField(
            model_name='parkowner',
            name='zone',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.IntegerField(choices=[], default=1),
        ),
        migrations.DeleteModel(
            name='Park_Detail',
        ),
        migrations.AddField(
            model_name='zone',
            name='park_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_zone', to='accounts.parkowner'),
        ),
        migrations.AddField(
            model_name='booking',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.zone'),
        ),
    ]
