# Generated by Django 4.2.13 on 2024-05-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_park_detail_park_plan_text_booking_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.IntegerField(choices=[], default=1),
        ),
    ]
