# Generated by Django 4.2.13 on 2024-05-17 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_subscription_booking_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='parkowner',
            name='subscription_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.IntegerField(choices=[('1', '1 Month'), ('2', '6 Month'), ('3', '12 Month')], default=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
