# Generated by Django 4.2.13 on 2024-05-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_booking_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkowner',
            name='zone',
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField()),
                ('park_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='accounts.parkowner')),
            ],
        ),
    ]
