# Generated by Django 4.2.13 on 2024-05-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_booking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='park_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_zones', to='accounts.parkowner'),
        ),
    ]
