# Generated by Django 4.2.13 on 2024-05-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_park_owner_id_zone_park_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='park_owner',
        ),
        migrations.AddField(
            model_name='slot',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='accounts.zone'),
        ),
    ]
