# Generated by Django 5.0 on 2024-05-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_slot_park_owner_slot_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.IntegerField(choices=[(1, '1 Hours'), (2, '3 Hours'), (3, '5 Hours')]),
        ),
        migrations.AlterField(
            model_name='parkowner',
            name='subscription_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('slot', 'status')},
        ),
    ]
