# Generated by Django 4.2.13 on 2024-05-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_booking_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkowner',
            name='capacity',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.IntegerField(choices=[(1, '1 Month'), (2, '6 Month'), (3, '12 Month')], default=1),
        ),
    ]
