# Generated by Django 4.2.13 on 2024-05-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_parkowner_capacity_alter_subscription_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkowner',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parkowner',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
