# Generated by Django 4.2.13 on 2024-05-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_parkowner_latitude_parkowner_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkowner',
            name='email',
        ),
        migrations.AddField(
            model_name='slot',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
