# Generated by Django 4.2.13 on 2024-05-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_parkowner_email_slot_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
