# Generated by Django 4.2.13 on 2024-05-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_booking_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
