# Generated by Django 4.2.13 on 2024-05-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_booking_customer_booking_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkowner',
            name='available_slot',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
