# Generated by Django 4.2.13 on 2024-06-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_subscriptionpackage_alter_subscription_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subscriptionpackage'),
        ),
    ]
