# Generated by Django 4.2.13 on 2024-06-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkowner',
            name='subscription_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.subscription'),
        ),
    ]
