# Generated by Django 4.2.13 on 2024-06-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_parkowner_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
